baseURL = "https://blog.johanet.fr/"


theme = "cocoa-eh"
publishdir = "/var/www/blog/"

builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
author = "Louis Johanet"
title = "Bits about software"
pluralizelisttitles = false

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Bits about software"
copyright = "Copyright © 2018 Louis Johanet"
logofile = "img/logo.png"
faviconfile = "img/logo.png"
highlightjs = true
progressively = true
align_left = false
lang = "en"
github = "ojathelonius"
email = "louis@johanet.fr"
linkedin = "louis-johanet"
posts_navigation = true
small_banner_logo = false
latestpostcount = 5

